Using tmp branch of j-b-a for support 2.9
canonical/charm-juju-backup-all pull request #54
Opened 2024-11-06 08:36 UTC by rgildein

We need to tmp support Juju 2.9, and charm need to use j-b-a python package with libjuju 2.9.

fixes: #53

2024-11-06 08:40 UTC, rgildein commented
This PR is blocked until the https://github.com/canonical/juju-backup-all/pull/58 is not merged to tmp branch.

2024-11-06 09:04 UTC, chanchiwai-ray requested changes
Blocked the PR until https://github.com/canonical/juju-backup-all/pull/58#pullrequestreview-2417620274 is merged

2024-11-06 09:25 UTC, Pjack approved these changes

2024-11-06 09:46 UTC, chanchiwai-ray approved these changes

2024-11-07 01:22 UTC, jneo8 approved these changes
Thanks, LGTM.

2024-11-07 09:07 UTC, merged